apps/detector/views.py
import random
import uuid
from pathlib import Path

import cv2
import numpy as np
import torch
import torchvision
from apps.app import db
from apps.crud.models import User

# UploadImageFormをimportする
from apps.detector.forms import DeleteForm, DetectorForm, UploadImageForm # DeletagForm
from apps.detector.models import UserImage, UserImageTag
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)

# login_required, current_userをimportする
from flask_login import current_user, login_required
from PIL import Image

# template_folderを指定する（staticは指定しない）
dt = Blueprint("detector", __name__, template_folder="templates")


# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/")
def index():
    # UserとUserImageをJoinして画像一覧を取得する
    user_images = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .all()
    )

    # タグ一覧を取得する
    user_image_tag_dict = {}
    for user_image in user_images:
        # 画像に紐づくタグ一覧を取得する
        user_image_tags = (
            db.session.query(UserImageTag)
            .filter(UserImageTag.user_image_id == user_image.UserImage.id)
            .all()
        )
        user_image_tag_dict[user_image.UserImage.id] = user_image_tags

    # 物体検知フォームをインスタンス化する
    detector_form = DetectorForm()
    # DeleteFormをインスタンス化する
    delete_form = DeleteForm()
    # DeletagFormをインスタンス化する
    # deletag_form = DeletagForm()

    return render_template(
        "detector/index.html",
        user_images=user_images,
        # タグ一覧をテンプレートに渡す
        user_image_tag_dict=user_image_tag_dict,
        # 物体検知フォームをテンプレートに渡す
        detector_form=detector_form,
        # 画像削除フォームをテンプレートに渡す
        delete_form=delete_form,
        # タグ削除フォームをテンプレートに渡す
        # deletag_form=deletag_form,
    )


@dt.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)


@dt.route("/upload", methods=["GET", "POST"])
# ログイン必須とする
@login_required
def upload_image():
    # UploadImageFormを利用してバリデーションをする
    form = UploadImageForm()
    if form.validate_on_submit():
        # アップロードされた画像ファイルを取得する
        file = form.image.data

        # ファイルのファイル名と拡張子を取得し、ファイル名をuuidに変換する
        ext = Path(file.filename).suffix
        image_uuid_file_name = str(uuid.uuid4()) + ext

        # 画像を保存する
        image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
        file.save(image_path)

        # DBに保存する
        user_image = UserImage(user_id=current_user.id, image_path=image_uuid_file_name)
        db.session.add(user_image)
        db.session.commit()

        return redirect(url_for("detector.index"))
    return render_template("detector/upload.html", form=form)


def make_color(labels):
    # 枠線の色をランダムに決定
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in labels]
    color = random.choice(colors)
    return color


def make_line(result_image):
    # 枠線を作成
    line = round(0.002 * max(result_image.shape[0:2])) + 1
    return line


def draw_lines(c1, c2, result_image, line, color):
    # 四角形の枠線を画像に追記
    cv2.rectangle(result_image, c1, c2, color, thickness=line)
    return cv2


def draw_texts(result_image, line, c1, cv2, color, labels, label):
    # 検知したテキストラベルを画像に追記
    display_txt = f"{labels[label]}"
    font = max(line - 1, 1)
    t_size = cv2.getTextSize(display_txt, 0, fontScale=line / 3, thickness=font)[0]
    c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3
    cv2.rectangle(result_image, c1, c2, color, -1)
    cv2.putText(
        result_image,
        display_txt,
        (c1[0], c1[1] - 2),
        0,
        line / 3,
        [255, 255, 255],
        thickness=font,
        lineType=cv2.LINE_AA,
    )
    return cv2

def exec_detect(target_image_path):
    # ラベルの読み込み
    labels = current_app.config["LABELS"]

    # 画像の読み込み
    image = Image.open(target_image_path)

    # 画像データをテンソル型の数値データへ変換
    image_tensor = torchvision.transforms.functional.to_tensor(image)

    # 学習済みモデルの読み込み
    model = torch.load(Path(current_app.root_path, "detector", "model.pt"))

    # モデルの推論モードに切り替え
    model = model.eval()

    # 推論の実行
    output = model([image_tensor])[0]
    tags = []
    result_image = np.array(image.copy())

    # 学習済みモデルが検知した各物体の分だけ画像に追記
    for box, label, score in zip(output["boxes"], output["labels"], output["scores"]):
        if score > 0.5 and labels[label] not in tags:
            print(score)
            print(labels[label])
            # 枠線の色の決定
            color = make_color(labels)
            # 枠線の作成
            line = make_line(result_image)
            # 検知画像の枠線とテキストラベルの枠線の位置情報
            c1 = (int(box[0]), int(box[1]))
            c2 = (int(box[2]), int(box[3]))
            # 画像に枠線を追記
            cv2 = draw_lines(c1, c2, result_image, line, color)
            # 画像にテキストラベルを追記
            cv2 = draw_texts(result_image, line, c1, cv2, color, labels, label)
            tags.append(labels[label])

    # 検知後の画像ファイル名を生成する
    detected_image_file_name = str(uuid.uuid4()) + ".jpg"

    # 画像コピー先パスを取得する
    detected_image_file_path = str(
        Path(current_app.config["UPLOAD_FOLDER"], detected_image_file_name)
    )
    # 変換後の画像ファイルを保存先へコピーする
    cv2.imwrite(detected_image_file_path, cv2.cvtColor(result_image, cv2.COLOR_RGB2BGR))
    return tags, detected_image_file_name


def save_detected_image_tags(user_image, tags, detected_image_file_name):
    # 検知後画像の保存先パスをDBに保存する
    user_image.image_path = detected_image_file_name
    # 検知フラグをTrueにする
    user_image.is_detected = True
    db.session.add(user_image)
    # user_images_tagsレコードを作成する
    for tag in tags:
        user_image_tag = UserImageTag(user_image_id=user_image.id, tag_name=tag)
        db.session.add(user_image_tag)
    db.session.commit()

@dt.route("/detect/<string:image_id>", methods=["POST"])
# login_requiredデコレーターをつけてログイン必須とする
@login_required
def detect(image_id):
    # user_imagesテーブルからレコードを取得する
    user_image = db.session.query(UserImage).filter(UserImage.id == image_id).first()
    if user_image is None:
        flash("物体検知対象の画像が存在しません。")
        return redirect(url_for("detector.index"))

    # 物体検知対象の画像パスを取得する
    target_image_path = Path(current_app.config["UPLOAD_FOLDER"], user_image.image_path)
    # 物体検知を実行してタグと変換後の画像パスを取得する
    tags, detected_image_file_name = exec_detect(target_image_path)

    try:
        # データベースにタグと変換後の画像パス情報を保存する
        save_detected_image_tags(user_image, tags, detected_image_file_name)
    except Exception as e:
        flash("物体検知処理でエラーが発生しました。")
        # ロールバックする
        db.session.rollback()
        # エラーログ出力
        current_app.logger.error(e)
        return redirect(url_for("detector.index"))
    return redirect(url_for("detector.index"))


@dt.route("/images/delete/<string:image_id>", methods=["POST"])
@login_required
def delete_image(image_id):
    try:
        # user_image_tagsテーブルからレコードを削除する
        db.session.query(UserImageTag).filter(
            UserImageTag.user_image_id == image_id
        ).delete()

        # user_imageテーブルからレコードを削除する
        db.session.query(UserImage).filter(UserImage.id == image_id).delete()

        db.session.commit()
    except Exception as e:
        flash("画像削除処理でエラーが発生しました。")
        # エラーログ出力
        current_app.logger.error(e)
        db.session.rollback()
    return redirect(url_for("detector.index"))

"""
@dt.route("/images/deletag/<string:image_id>", methods=["POST"])
# login_requiredデコレーターをつけてログイン必須とする
@login_required
def deletag(image_id):
    # user_imagesテーブルからレコードを取得する
    user_image = db.session.query(UserImage).filter(UserImage.id == image_id).first()
    if user_image is None:
        flash("タグ削除対象の画像が存在しません。")
        return redirect(url_for("detector.index"))

    # タグ削除対象の画像パスを取得する
    target_image_path = Path(current_app.config["UPLOAD_FOLDER"], user_image.image_path)
    # 物体検知を実行してタグと変換後の画像パスを取得する
    tags, detected_image_file_name = exec_detect(target_image_path)

    try:
        # データベースにタグと変換後の画像パス情報を保存する
        save_detected_image_tags(user_image, tags, detected_image_file_name)
    except Exception as e:
        flash("物体検知処理でエラーが発生しました。")
        # ロールバックする
        db.session.rollback()
        # エラーログ出力
        current_app.logger.error(e)
        return redirect(url_for("detector.index"))
    return redirect(url_for("detector.index"))
"""

@dt.route("/images/search", methods=["GET"])
def search():
    # 画像一覧を取得する
    user_images = db.session.query(User, UserImage).join(
        UserImage, User.id == UserImage.user_id
    )

    # GETパラメータから検索ワードを取得する
    search_text = request.args.get("search")

    user_image_tag_dict = {}
    filtered_user_images = []

    # user_imagesをループしuser_imagesに紐づくタグ情報を検索する
    for user_image in user_images:
        # 検索ワードが空の場合はすべてのタグを取得する
        if not search_text:
            # タグ一覧を取得する
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )
        else:
            # 検索ワードで絞り込んだタグを取得する
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .filter(UserImageTag.tag_name.like("%" + search_text + "%"))
                .all()
            )

            # タグが見つからなかったら画像を返さない
            if not user_image_tags:
                continue

            # タグがある場合はタグ情報を取得しなおす
            user_image_tags = (
                db.session.query(UserImageTag)

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>Detectagram</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>

<body>
    <!-- ナビゲーションバーを作成する -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">　
        <div class="container">
            <a class="navbar-brand " href="{{ url_for('detector.index') }}">Detectagram</a>
            <!-- 画像検索フォームを追加する -->
            {% if url_for(request.endpoint) == url_for('detector.index') or
            url_for(request.endpoint) == url_for('detector.search') %}
            <div class="btn-group">
                <form method="GET" action="{{ url_for('detector.search') }}" name="dtSearchForm">
                    {% if request.args.get("search") %}
                    <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="検索"
                        name="search" value="{{ request.args.get('search') }}" />
                    {% else %}
                    <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="検索"
                        name="search" />
                    {% endif %}
                </form>
            </div>
            {% endif %}
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>
</body>

</html>

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}

<!-- flashエラーを表示する -->
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li class="flash">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

<!-- 画像一覧を表示する -->
{% for user_image in user_images %}
<div class="card col-md-7 dt-image-content">
    <header class="d-flex justify-content-between">
        <!-- {{ user_image.User.username }} -->
        <div class="dt-image-username"><font face="San Francisco"><b><h3>Detectagram</h3></b></font></div>
        <!-- 物体検知フォームを追加する -->
        <div class="d-flex flex-row-reverse">
            <div class="p-2">
                <form action="{{ url_for('detector.detect', image_id=user_image.UserImage.id) }}" method="POST">
                    {{ detector_form.csrf_token }}
                    {% if current_user.id == user_image.User.id and user_image.UserImage.is_detected == False %}
                    {{detector_form.submit(class="btn btn-primary")}}
                    {% else %}
                    {{ detector_form.submit(class="btn btn-primary",disabled="disabled")}}
                    {% endif %}
                </form>
            </div>
        </div>
    </header>
    <section>
        <img src="{{ url_for('detector.image_file', filename=user_image.UserImage.image_path) }}" alt="アップロード画像" />
    </section>
    <footer>
        {% if user_image_tag_dict[user_image.UserImage.id] %}
        {% set sorted_tags = user_image_tag_dict[user_image.UserImage.id]|sort(attribute='tag_name') %}
        {% endif %}
        {% set tag_counter = {} %}
        {% for tag in sorted_tags %}
        {% set tag_name = tag.tag_name %}
        {% if tag_counter.get(tag_name, 0) > 0 %}
        {% set tag_name = tag_name ~ tag_counter.get(tag_name) %}
        {% endif %}
        #{{ tag_name }}
        {% set tag_counter = tag_counter.update({tag.tag_name: tag_counter.get(tag.tag_name, 0) + 1}) %}
        {% endfor %}
    </footer>
    <style>/*
    <!-- リロードアニメーションを表示する -->
    <div id="reload-animation" class="text-center" style="display: none;">
        <img src="path/to/your/loading-image" />
    </div>
    <!-- リロードボタンを追加する -->
    <div style="padding-left: 0px;">
        <div class="col-md-10 text-right dt-image-reload-btn">
            <button id="reload-button" class="btn btn-primary">リロード</button>
        </div>
    </div>
    <!-- JavaScriptを追加する -->
    <script>
    $(function () {
        $("#reload-button").click(function () {
            $("#reload-animation").show();
            setTimeout(function () {
                location.reload();
            }, 3000); // 3秒後にリロード
        });
    });
    </script>
    */</style>
    
    <div class="d-flex flex-row-reverse">
        <!-- 画像削除ボタンのフォームを追加する -->
        <div class="p-2">
            <form action="{{ url_for('detector.delete_image', image_id=user_image.UserImage.id) }}" method="POST">
                {{ delete_form.csrf_token }}
                {% if current_user.id == user_image.User.id %}
                {{ delete_form.submit(class="btn btn-danger") }}
                {% else %}
                {{ delete_form.submit(class="btn btn-danger", disabled="disabled") }}
                {% endif %}
            </form>
        </div>
    </div>
</div>
</div>
{% endfor %}
<div style="padding-bottom: 30px;">
    <!-- 画像アップロード画面へのリンクを追加する -->
    <div class="col-md-10 text-right dt-image-register-btn">
        <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">画像新規登録</a>
    </div>
</div>
{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}
{% block content %}
<div>
    <h4>画像新規登録</h4>
    <p>アップロードする画像を選択してください</p>
    <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data"
        novalidate="novalidate">
        {{ form.csrf_token }}
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
</div>
{% endblock %}